<?php
/*
Plugin Name: CogDog's WP Embed Docsify This
Plugin URI: https://github.com/cogdog/wp-embed-docsify-this
Description: Autoembed links generated by Docsify This
Version: 0.1
License: GPLv2
Author: Alan Levine
Author URI: https://cog.dog
*/


// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

define('EMBED_EXTRAS_PLUGIN_VERSION', '0.1');


function cogdog_docsify_this_register_embeds() {

	// enable as an oembed provider
	
	//handler for Docsify-This 
	wp_embed_register_handler(
		'docsify-this',
		'#^https://docsify-this\.net\/\?basePath=(.*)$#i',
		'cogdog_handler_docsify_this'
	);
}

add_action( 'init', 'cogdog_docsify_this_register_embeds' );

function cogdog_handler_docsify_this( $matches, $attr, $url, $rawattr ) {

	$embed = 
		'<div style="width: 100%; margin: 0; padding: 0; overflow: hidden;" class="docsify-this-embed"><iframe src="https://docsify-this.net/?basePath=' . esc_attr($matches[1])  . '"  style="width: 100%; height: 2700px; border: none; display: block;" scrolling="no" frameborder="0"></iframe></div>';

	return $embed;
}
?>
